protein = float(input('Введите массу белков в продукте (г)'))
fat = float(input('Введите массу жиров в продукте (г)'))
carbohydrate = float(input('Введите массу углеводов в продукте (г)'))
calories = (protein * 4) + (fat * 9) + (carbohydrate * 4)
print(calories)