dna = input("Введите последовтельность ДНК: ").upper()
print(f'Последовательность в верхнем регистре: {dna}')
print('Подсчет нуклеотидов: ')
a = count_A = dna.count("A")
t = count_T = dna.count('T')
g = count_G = dna.count('G')
c = count_C = dna.count('C')
print(f'A: {a}')
print(f'T: {t}')
print(f'G: {g}')
print(f'C: {c}')
b = len(dna)
print('Общая длина: ',b, 'нуклеотидов')
print('Процентное содержание: ')
print('A:', round(a/b*100, 0),'%') 
print('T:', round(t/b*100, 0),'%')
print('G:', round(g/b*100, 0),'%')
print('C:', round(c/b*100, 0),'%')
